allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  workerd: set this to true or false
minimumReleaseAgeExclude:
  - miniflare@4.20260521.0
  - wrangler@4.94.0
