name = "nano-rag"
main = ".open-next/worker.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"
CHAT_MODEL = "mistral-medium-2508"

[[d1_databases]]
binding = "DB"
database_name = "nano-rag-production-db"
database_id = "67734952-49a6-48cc-ac61-1d8d0d055ddc"

[observability]
enabled = true
head_sampling_rate = 1